- name: Configure Consul Backups
  hosts: tags_consul_server
  tasks:
    - name: Install Dependencies
      ansible.builtin.apt:
        name:
          - nfs-common
        state: present
        update_cache: true

    - name: Place Consul Backup Script
      ansible.builtin.template:
        src: "consul.sh.j2"
        dest: "/usr/sbin/backup-consul.sh"
        mode: "0555"

    - name: Install Crontab
      ansible.builtin.cron:
        name: backup-consul
        minute: 0
        hour: "*/4"
        job: "bash /usr/sbin/backup-consul.sh > /var/log/consul-backup.log 2>&1"

- name: Configure Nomad Backups
  hosts: tags_nomad
  tasks:
    - name: Install Dependencies
      ansible.builtin.apt:
        name:
          - nfs-common
        state: present
        update_cache: true

    - name: Place Nomad Backup Script
      ansible.builtin.template:
        src: "nomad.sh.j2"
        dest: "/usr/sbin/backup-nomad.sh"
        mode: "0555"

    - name: Install Crontab
      ansible.builtin.cron:
        name: backup-nomad
        minute: 0
        hour: "*/4"
        job: "bash /usr/sbin/backup-nomad.sh > /var/log/nomad-backup.log 2>&1"

- name: Allow Access to Share
  hosts: device_roles_storage
  environment:
    middleware_method: client
  vars:
    allowed_host_ips: "{{ groups['tags_nomad'] | union(groups['tags_consul_server']) | map('extract', hostvars, 'ansible_host') | list | sort }}"
  tasks:
    - name: Update Raft Share  # noqa: args[module]
      arensb.truenas.sharing_nfs:
        name: "Server Backups - Rafts"
        path: "/mnt/tank/Server Backups/Raft Backups"
        hosts: "{{ allowed_host_ips }}"
