version: '3'
services:
  cloudflared:
    image: "cloudflare/cloudflared:latest"
    container_name: "cloudflared"
    command:
      - "tunnel"
      - "run"
      - "--token"
      - "{{ tunnel_token }}"
    network_mode: host
    restart: unless-stopped
