---
# - name: Auto Highstate
#   ansible.builtin.import_playbook: ansible-applier.yaml
- name: Common Configuration
  ansible.builtin.import_playbook: common.yaml
- name: TrueNAS
  ansible.builtin.import_playbook: truenas.yaml
- name: Home Assistant
  ansible.builtin.import_playbook: home-assistant.yaml
- name: Warp
  ansible.builtin.import_playbook: warp.yaml
