---
- name: Deploy Warp Tunnel
  hosts: tags_warp

  vars:
    docker_config:
      metrics-addr: "0.0.0.0:9323"

  roles:
    - docker

  tasks:
    - name: Create Cloudflare Tunnel Token Secret
      community.docker.docker_secret:
        name: cf_tunnel_token
        data: "{{ cf_tunnel_token | b64encode }}"
        data_is_b64: true
        state: present

    - name: Create and start Warp Tunnel
      community.docker.docker_compose:
        project_src: compose/warp
      register: output

    - name: Show results
      ansible.builtin.debug:
        var: output
