---
- name: Deploy Warp Tunnel
  hosts: tags_warp
  become: true

  vars:
    docker_config:
      metrics-addr: "0.0.0.0:9323"

  roles:
    - docker

  tasks:
    - name: Create and start Warp Tunnel
      vars:
        dir: /var/docker-compose-files/warp
      block:
        - name: Create Dir
          ansible.builtin.file:
            path: "{{ dir }}"
            state: directory
            recurse: true
            mode: "0700"
        - name: Place Compose File
          ansible.builtin.template:
            src: compose/warp/docker-compose.yaml
            dest: "{{ dir }}/docker-compose.yaml"
            mode: "0600"

        - name: Compose Up
          ansible.builtin.command:
            cmd: "docker compose up -d"
            chdir: "{{ dir }}"
          register: output
          changed_when: '"Started" in output.stderr'

        - name: Show results
          ansible.builtin.debug:
            var: output

    - name: Show results
      ansible.builtin.debug:
        var: output
