---
- name: Deploy Warp Tunnel
  hosts: tags_warp
  become: true

  tasks:
    - name: Create keyrings directory
      ansible.builtin.file:
        path: /usr/share/keyrings
        state: directory
        mode: '0755'

    - name: Download Cloudflare GPG key
      ansible.builtin.get_url:
        url: https://pkg.cloudflare.com/cloudflare-main.gpg
        dest: /usr/share/keyrings/cloudflare-main.gpg
        mode: '0644'
        use_proxy: false

    - name: Add Cloudflare repository to apt sources
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/cloudflared.list
        line: 'deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared bookworm main'
        create: true
        mode: '0644'

    - name: Update apt package list
      ansible.builtin.apt:
        update_cache: true

    - name: Install cloudflared
      ansible.builtin.apt:
        name: cloudflared
        state: present

    - name: Install Cloudflared service
      ansible.builtin.command: "cloudflared service install {{ tunnel_token }}"
      args:
        creates: /etc/systemd/system/cloudflared.service

    - name: Clean up the GPG key and repository file
      ansible.builtin.file:
        path: /usr/share/keyrings/cloudflare-main.gpg
        state: absent

    - name: Clean up the Cloudflare repository list file
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/cloudflared.list
        state: absent
