---
collections:
  - name: community.general
    version: 12.3.0
  - name: ansible.posix
    version: 2.1.0
  - name: ansible.utils
    version: 6.0.1
  - name: arensb.truenas
    version: 1.14.4
  - name: netbox.netbox
    version: 3.22.0
  - name: prometheus.prometheus
    version: 0.27.6

roles:
  - name: xanmanning.k3s
    version: v3.6.2
