---
collections:
  - name: community.general
    version: 11.0.0
  - name: ansible.posix
    version: 2.0.0
  - name: ansible.utils
    version: 6.0.0
  - name: arensb.truenas
    version: 1.11.5
  - name: netbox.netbox
    version: 3.21.0
  - name: prometheus.prometheus
    version: 0.27.0

roles:
  - name: xanmanning.k3s
    version: v3.4.4
