---
collections:
  - name: community.general
    version: 9.1.0
  - name: ansible.posix
    version: 1.5.4
  - name: ansible.utils
    version: 5.0.0
  - name: arensb.truenas
    version: 1.9.5
  - name: netbox.netbox
    version: 3.19.1
  - name: prometheus.prometheus
    version: 0.17.0

roles:
  - name: xanmanning.k3s
    version: v3.4.4
