---
collections:
  - name: community.general
    version: 10.5.0
  - name: ansible.posix
    version: 2.0.0
  - name: ansible.utils
    version: 5.1.2
  - name: arensb.truenas
    version: 1.10.0
  - name: netbox.netbox
    version: 3.21.0
  - name: prometheus.prometheus
    version: 0.26.1

roles:
  - name: xanmanning.k3s
    version: v3.4.4
