---
collections:
  - name: community.general
    version: 9.5.0
  - name: ansible.posix
    version: 1.6.0
  - name: ansible.utils
    version: 5.1.2
  - name: arensb.truenas
    version: 1.9.5
  - name: netbox.netbox
    version: 3.20.0
  - name: prometheus.prometheus
    version: 0.19.0

roles:
  - name: xanmanning.k3s
    version: v3.4.4
