- name: Unlock All Restic Backends
  hosts: device_roles_storage

  vars:
    shares:
      - Photos
      - Docs
      - Mel
      - Tom
      - Archive

  tasks:
    - name: Unlock
      loop: "{{ shares }}"
      ansible.builtin.command: "/usr/bin/restic unlock"
      environment: &restic_env
        RESTIC_REPOSITORY: "s3:{{ b2_s3_endpoint }}/{{ offsite_b2_bucket_name }}/{{ item }}"
        RESTIC_PASSWORD: "{{ offsite_restic_password }}"
        AWS_ACCESS_KEY_ID: "{{ b2_account_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ b2_account_key }}"
      register: unlock
      changed_when: '"successfully removed" in unlock.stdout'
