---
- name: Execute Debian dist upgrade
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Check if reboot required
      ansible.builtin.stat:
        path: /run/reboot-required
        get_checksum: false
      register: reboot_required_file
    - name: Abort if Reboot Required
      ansible.builtin.meta: end_host
      when: reboot_required_file.stat.exists
    - name: Switch OS from bookworm to trixie
      ansible.builtin.replace:
        path: /etc/apt/sources.list
        regexp: 'bookworm'
        replace: 'trixie'
      become: true
    - name: Find all 3rd-party repos
      ansible.builtin.find:
        paths: /etc/apt/sources.list.d
        patterns: '*'
        recurse: false
      register: third_party_repos
    - name: Switch 3rd-party repos from bookworm to trixie
      ansible.builtin.replace:
        path: "{{ item.path }}"
        regexp: 'bookworm'
        replace: 'trixie'
      loop: "{{ third_party_repos.files }}"
      loop_control:
        label: "{{ item.path }}"
      become: true
    - name: Use apt to move to trixie
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true
      become: true
    - name: Get distribution version
      ansible.builtin.setup:
        filter: ansible_distribution*
    - name: Fail if not Debian 13
      ansible.builtin.assert:
        that:
          - ansible_facts['distribution_major_version'] == '13'
        fail_msg: "Upgrade to Debian 13 failed"
    - name: Require Reboot
      ansible.builtin.file:
        path: /run/reboot-required
        state: touch
        mode: u=rw,g=r,o=r
    - name: Apt autoremove
      ansible.builtin.apt:
        autoremove: true
      become: true
