---
- name: Update and reboot system
  hosts: device_roles_compute
  become: true
  serial: 1

  tasks:
    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: true

    - name: Check for packages to update   # noqa: command-instead-of-module
      ansible.builtin.shell: |
        set -o pipefail;
        apt-get -s upgrade docker-ce nomad consul | grep "Inst"
      args:
        executable: /bin/bash
      register: package_updates
      changed_when: false
      failed_when: package_updates.rc > 1

    - name: Stop Nomad service if specific packages are being updated
      ansible.builtin.systemd:
        name: nomad
        state: stopped
      when: package_updates.stdout_lines | length > 0

    - name: Perform system-wide upgrade
      ansible.builtin.apt:
        upgrade: full
        autoremove: true
        autoclean: true

    - name: Check if reboot is required
      ansible.builtin.command: test -f /var/run/reboot-required
      changed_when: false
      register: reboot_required
      failed_when: false

    - name: Reboot the system if necessary
      ansible.builtin.reboot:
        reboot_timeout: 300
        msg: "Reboot initiated by Ansible for package updates"
      when: reboot_required.rc == 0
      async: 0
      poll: 0
      failed_when: false

    - name: Wait for the system to reboot
      delegate_to: localhost
      ansible.builtin.wait_for_connection:
        connect_timeout: 5
        sleep: 5
      when: reboot_required.rc == 0

    - name: Filter Services to Start  # noqa: command-instead-of-module
      ansible.builtin.shell: systemctl is-active {{ item }} >/dev/null 2>&1
      register: service_status
      failed_when: false
      changed_when: false
      loop:
        - consul
        - docker
        - weave
        - weave-expose
        - nomad
      ignore_errors: true

    - name: Start Services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
      loop: "{{ service_status.results | selectattr('rc', 'eq', 0) | map(attribute='item') | list }}"
