---
- name: Install Unbound Exporter on FreeBSD
  hosts: device_roles_firewall
  become: true
  gather_facts: true

  vars:
    unbound_exporter_version: "v0.4.6"
    exporter_local_path: /tmp/unbound-exporter

    bin_path: /usr/local/sbin/unbound_exporter

  tasks:
    - name: Clone Unbound Exporter repository
      ansible.builtin.git:
        repo: https://github.com/letsencrypt/unbound_exporter.git
        dest: '{{ exporter_local_path }}'
        version: "{{ unbound_exporter_version }}"
      delegate_to: localhost
      become: false

    - name: Cross-compile binary  # noqa: command-instead-of-shell
      ansible.builtin.shell: go build -o {{ exporter_local_path }}/unbound_exporter -v
      args:
        chdir: '{{ exporter_local_path }}'
      environment:
        GOOS: freebsd
        GOARCH: amd64
      delegate_to: localhost
      changed_when: true
      become: false

    - name: Copy Unbound Exporter binary
      ansible.builtin.copy:
        src: '{{ exporter_local_path }}/unbound_exporter'
        dest: '{{ bin_path }}'
        mode: "0755"

    - name: Cleanup Build Directory
      ansible.builtin.file:
        path: "{{ exporter_local_path }}"
        state: absent
      delegate_to: localhost
      become: false

    - name: Create RC service directory
      ansible.builtin.file:
        path: /usr/local/etc/rc.d
        state: directory
        mode: "0644"

    - name: Create Exporter rc.d script
      vars:
        name: unbound_exporter
        binary_path: "{{ bin_path }}"
      ansible.builtin.template:
        src: router/unbound_exporter_rc.j2
        dest: /usr/local/etc/rc.d/unbound_exporter
        mode: "0755"

    - name: Allow Read Access to Keys
      ansible.builtin.command: chmod 660 /var/unbound/unbound_control.key

    - name: Add Root to Unbound Group
      ansible.builtin.command: pw group mod unbound -m root

    - name: Enable Exporter service
      ansible.builtin.command: sysrc unbound_exporter_enable=YES
      changed_when: true

    - name: Start Exporter service
      ansible.builtin.service:
        name: unbound_exporter
        state: restarted
        enabled: true
