---
- name: Install CoreDNS on FreeBSD
  hosts: device_roles_firewall
  become: true
  gather_facts: true

  vars:
    coredns_version: "v1.10.1"

    coredns_local_path: /tmp/coredns

  tasks:
    - name: Clone CoreDNS repository
      ansible.builtin.git:
        repo: https://github.com/coredns/coredns.git
        dest: '{{ coredns_local_path }}'
        version: "{{ coredns_version }}"
      delegate_to: localhost
      become: false

    - name: Cross-compile CoreDNS binary  # noqa: command-instead-of-shell
      ansible.builtin.shell: go build -o /tmp/coredns/coredns -v
      args:
        chdir: '{{ coredns_local_path }}'
      environment:
        GOOS: freebsd
        GOARCH: amd64
      delegate_to: localhost
      changed_when: true
      become: false

    - name: Copy CoreDNS binary
      ansible.builtin.copy:
        src: '{{ coredns_local_path }}/coredns'
        dest: /usr/local/sbin/coredns
        mode: "0755"

    - name: Cleanup Build Directory
      ansible.builtin.file:
        path: "{{ coredns_local_path }}"
        state: absent
      delegate_to: localhost
      become: false

    - name: Create CoreDNS service directory
      ansible.builtin.file:
        path: /usr/local/etc/rc.d
        state: directory
        mode: "0644"

    - name: Create CoreDNS rc.d script
      ansible.builtin.template:
        src: router/coredns_rc.j2
        dest: /usr/local/etc/rc.d/coredns
        mode: "0755"

    - name: Create CoreDNS configuration directory
      ansible.builtin.file:
        path: /etc/coredns
        state: directory
        mode: "0755"

    - name: Copy Corefile
      ansible.builtin.template:
        src: router/Corefile.j2
        dest: /etc/coredns/Corefile
        mode: "0644"

    - name: Enable CoreDNS service
      ansible.builtin.command: sysrc coredns_enable=YES
      changed_when: true

    - name: Start CoreDNS service
      ansible.builtin.service:
        name: coredns
        state: restarted
        enabled: true
