version: '3'
services:
  traefik:
    image: "traefik:v3.2"
    container_name: "traefik"
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--entrypoints.websecure.http.tls.certResolver=cf_wss"
      - "--entrypoints.traefik.address=:9000/tcp"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.priority=10"
      - "--certificatesresolvers.cf_wss.acme.dnschallenge=true"
      - "--certificatesresolvers.cf_wss.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.cf_wss.acme.email=admin@whiterstar.systems"
      - "--certificatesresolvers.cf_wss.acme.storage=/letsencrypt/acme.json"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--ping=true"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.entrypoint=traefik"

    network_mode: host
    environment:
      - CF_DNS_API_TOKEN={{ cf_token }}

    volumes:
      - "/etc/docker-data/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

    restart: unless-stopped
    read_only: true
    security_opt:
      - no-new-privileges:true

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homeassistant.rule=Host(`home.paulus.family`)"
      - "traefik.http.routers.homeassistant.entrypoints=web,websecure"
      - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"
    volumes:
      - /etc/docker-data/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    security_opt:
      - no-new-privileges:true

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
    restart: unless-stopped
    read_only: true
    security_opt:
      - no-new-privileges:true

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.50.0
    container_name: cadvisor
    command:
      - "--store_container_labels=false"
      - "--docker_only=true"
      - "--disable_root_cgroup_stats=true"
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped
    read_only: true
    security_opt:
      - no-new-privileges:true