version: '3'
services:
  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--entrypoints.websecure.http.tls.certResolver=cf_wss"
      - "--entrypoints.traefik.address=:9000/tcp"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.priority=10"
      - "--certificatesresolvers.cf_wss.acme.dnschallenge=true"
      - "--certificatesresolvers.cf_wss.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.cf_wss.acme.email=admin@whiterstar.systems"
      - "--certificatesresolvers.cf_wss.acme.storage=/letsencrypt/acme.json"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--ping=true"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.entrypoint=traefik"
    
    network_mode: host
    environment:
      - CF_DNS_API_TOKEN={{ cf_token }}

    volumes:
      - "/etc/docker-data/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

    restart: unless-stopped

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homeassistant.rule=Host(`home.whitestar.systems`)"
      - "traefik.http.routers.homeassistant.entrypoints=web,websecure"
      - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"
    volumes:
      - /etc/docker-data/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
    restart: unless-stopped
