{{ ansible_managed | comment }}

[providers.docker]
  exposedByDefault = false

[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      priority = 1

  [entryPoints.websecure]
    address = ":443"
    asDefault = true
    [entryPoints.websecure.http.tls]
      certResolver = "cf_wss"

  [entryPoints.traefik]
    address = ":9000/tcp"

[certificatesResolvers.cf_wss.acme]
  email = "admin@whiterstar.systems"
  storage = "/letsencrypt/acme.json"
  [certificatesResolvers.cf_wss.acme.dnsChallenge]
    provider = "cloudflare"

[api]
  dashboard = true
  insecure = true

[ping]

[metrics.prometheus]
  entryPoint = "traefik"

